// AngularProject/src/main/webapp/app/entities/role-user-my-suffix/detail/role-user-my-suffix-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { IRoleUserMySuffix } from '../role-user-my-suffix.model';

@Component({
  standalone: true,
  selector: 'jhi-role-user-my-suffix-detail',
  templateUrl: './role-user-my-suffix-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class RoleUserMySuffixDetailComponent {
  roleUser = input<IRoleUserMySuffix | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (roleUser()) {
      <div>
        <h2 data-cy="roleUserDetailsHeading"><span jhiTranslate="photoStoreApp.roleUser.detail.title">Role User</span></h2>

        <hr />

        <jhi-alert-error></jhi-alert-error>

        <jhi-alert></jhi-alert>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="photoStoreApp.roleUser.id">Id</span></dt>
          <dd>
            <span>{{ roleUser()!.id }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.roleUser.userId">User Id</span></dt>
          <dd>
            <span>{{ roleUser()!.userId?.id }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.roleUser.roleId">Role Id</span></dt>
          <dd>
            @if (roleUser()!.roleId) {
              <div>
                <a [routerLink]="['/role-my-suffix', roleUser()!.roleId?.id, 'view']">{{ roleUser()!.roleId?.id }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/role-user-my-suffix', roleUser()!.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>

// Project/src/main/webapp/app/entities/role-user-my-suffix/role-user-my-suffix-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import {} from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './role-user-my-suffix.reducer';

export const RoleUserMySuffixDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const roleUserEntity = useAppSelector(state => state.roleUser.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="roleUserDetailsHeading">Role User</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">Id</span>
          </dt>
          <dd>{roleUserEntity.id}</dd>
          <dt>User Id</dt>
          <dd>{roleUserEntity.userId ? roleUserEntity.userId.id : ''}</dd>
          <dt>Role Id</dt>
          <dd>{roleUserEntity.roleId ? roleUserEntity.roleId.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/role-user-my-suffix" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/role-user-my-suffix/${roleUserEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default RoleUserMySuffixDetail;
