// Project/src/main/webapp/app/entities/role-user-my-suffix/role-user-my-suffix-delete-dialog.tsx
import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { getEntity, deleteEntity } from './role-user-my-suffix.reducer';

export const RoleUserMySuffixDeleteDialog = () => {
  const dispatch = useAppDispatch();

  const pageLocation = useLocation();
  const navigate = useNavigate();
  const { id } = useParams<'id'>();

  const [loadModal, setLoadModal] = useState(false);

  useEffect(() => {
    dispatch(getEntity(id));
    setLoadModal(true);
  }, []);

  const roleUserEntity = useAppSelector(state => state.roleUser.entity);
  const updateSuccess = useAppSelector(state => state.roleUser.updateSuccess);

  const handleClose = () => {
    navigate('/role-user-my-suffix');
  };

  useEffect(() => {
    if (updateSuccess && loadModal) {
      handleClose();
      setLoadModal(false);
    }
  }, [updateSuccess]);

  const confirmDelete = () => {
    dispatch(deleteEntity(roleUserEntity.id));
  };

  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="roleUserDeleteDialogHeading">
        Confirm delete operation
      </ModalHeader>
      <ModalBody id="onlineShopApp.roleUser.delete.question">Are you sure you want to delete Role User {roleUserEntity.id}?</ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp; Cancel
        </Button>
        <Button id="jhi-confirm-delete-roleUser" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp; Delete
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default RoleUserMySuffixDeleteDialog;

// AngularProject/src/main/webapp/app/entities/role-user-my-suffix/delete/role-user-my-suffix-delete-dialog.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { ITEM_DELETED_EVENT } from 'app/config/navigation.constants';
import { IRoleUserMySuffix } from '../role-user-my-suffix.model';
import { RoleUserMySuffixService } from '../service/role-user-my-suffix.service';

@Component({
  standalone: true,
  templateUrl: './role-user-my-suffix-delete-dialog.component.html',
  imports: [SharedModule, FormsModule],
})
export class RoleUserMySuffixDeleteDialogComponent {
  roleUser?: IRoleUserMySuffix;

  protected roleUserService = inject(RoleUserMySuffixService);
  protected activeModal = inject(NgbActiveModal);

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.roleUserService.delete(id).subscribe(() => {
      this.activeModal.close(ITEM_DELETED_EVENT);
    });
  }
}

@if (roleUser) {
  <form name="deleteForm" (ngSubmit)="confirmDelete(roleUser.id!)">
    <div class="modal-header">
      <h4 class="modal-title" data-cy="roleUserDeleteDialogHeading" jhiTranslate="entity.delete.title">Confirm delete operation</h4>

      <span class="btn btn-close" data-dismiss="modal" aria-hidden="true" (click)="cancel()"></span>
    </div>

    <div class="modal-body">
      <jhi-alert-error></jhi-alert-error>
      <p id="jhi-delete-roleUser-heading" jhiTranslate="photoStoreApp.roleUser.delete.question" [translateValues]="{ id: roleUser.id }">
        Are you sure you want to delete Role User {{ roleUser.id }}?
      </p>
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
        <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
      </button>

      <button id="jhi-confirm-delete-roleUser" data-cy="entityConfirmDeleteButton" type="submit" class="btn btn-danger">
        <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
      </button>
    </div>
  </form>
}
