// Project/src/main/webapp/app/entities/photo-my-suffix/photo-my-suffix-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { openFile, byteSize, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './photo-my-suffix.reducer';

export const PhotoMySuffixDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const photoEntity = useAppSelector(state => state.photo.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="photoDetailsHeading">Photo</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">Id</span>
          </dt>
          <dd>{photoEntity.id}</dd>
          <dt>
            <span id="photo">Photo</span>
          </dt>
          <dd>
            {photoEntity.photo ? (
              <div>
                {photoEntity.photoContentType ? (
                  <a onClick={openFile(photoEntity.photoContentType, photoEntity.photo)}>
                    <img src={`data:${photoEntity.photoContentType};base64,${photoEntity.photo}`} style={{ maxHeight: '30px' }} />
                  </a>
                ) : null}
                <span>
                  {photoEntity.photoContentType}, {byteSize(photoEntity.photo)}
                </span>
              </div>
            ) : null}
          </dd>
          <dt>
            <span id="date">Date</span>
          </dt>
          <dd>{photoEntity.date ? <TextFormat value={photoEntity.date} type="date" format={APP_LOCAL_DATE_FORMAT} /> : null}</dd>
          <dt>
            <span id="state">State</span>
          </dt>
          <dd>{photoEntity.state}</dd>
          <dt>Portfolio</dt>
          <dd>{photoEntity.portfolio ? photoEntity.portfolio.id : ''}</dd>
          <dt>Cart</dt>
          <dd>{photoEntity.cart ? photoEntity.cart.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/photo-my-suffix" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/photo-my-suffix/${photoEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default PhotoMySuffixDetail;

// AngularProject/src/main/webapp/app/entities/photo-my-suffix/detail/photo-my-suffix-detail.component.ts
import { Component, inject, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { DataUtils } from 'app/core/util/data-util.service';
import { IPhotoMySuffix } from '../photo-my-suffix.model';

@Component({
  standalone: true,
  selector: 'jhi-photo-my-suffix-detail',
  templateUrl: './photo-my-suffix-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class PhotoMySuffixDetailComponent {
  photo = input<IPhotoMySuffix | null>(null);

  protected dataUtils = inject(DataUtils);

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (photo()) {
      <div>
        <h2 data-cy="photoDetailsHeading"><span jhiTranslate="photoStoreApp.photo.detail.title">Photo</span></h2>

        <hr />

        <jhi-alert-error></jhi-alert-error>

        <jhi-alert></jhi-alert>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="photoStoreApp.photo.id">Id</span></dt>
          <dd>
            <span>{{ photo()!.id }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.photo.photo">Photo</span></dt>
          <dd>
            @if (photo()!.photo) {
              <div>
                <a (click)="openFile(photo()!.photo ?? '', photo()!.photoContentType)">
                  <img [src]="'data:' + photo()!.photoContentType + ';base64,' + photo()!.photo" style="max-width: 100%" alt="photo" />
                </a>
                {{ photo()!.photoContentType }}, {{ byteSize(photo()!.photo ?? '') }}
              </div>
            }
          </dd>
          <dt><span jhiTranslate="photoStoreApp.photo.date">Date</span></dt>
          <dd>
            <span>{{ photo()!.date | formatMediumDate }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.photo.state">State</span></dt>
          <dd>
            <span [jhiTranslate]="'photoStoreApp.PhotoState.' + (photo()!.state ?? 'null')">{{
              { null: '', ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE' }[photo()!.state ?? 'null']
            }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.photo.portfolio">Portfolio</span></dt>
          <dd>
            @if (photo()!.portfolio) {
              <div>
                <a [routerLink]="['/portfolio-my-suffix', photo()!.portfolio?.id, 'view']">{{ photo()!.portfolio?.id }}</a>
              </div>
            }
          </dd>
          <dt><span jhiTranslate="photoStoreApp.photo.cart">Cart</span></dt>
          <dd>
            @if (photo()!.cart) {
              <div>
                <a [routerLink]="['/cart-my-suffix', photo()!.cart?.id, 'view']">{{ photo()!.cart?.id }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/photo-my-suffix', photo()!.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>
