// AngularProject/src/main/webapp/app/entities/cart-my-suffix/detail/cart-my-suffix-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { ICartMySuffix } from '../cart-my-suffix.model';

@Component({
  standalone: true,
  selector: 'jhi-cart-my-suffix-detail',
  templateUrl: './cart-my-suffix-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class CartMySuffixDetailComponent {
  cart = input<ICartMySuffix | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (cart()) {
      <div>
        <h2 data-cy="cartDetailsHeading"><span jhiTranslate="photoStoreApp.cart.detail.title">Cart</span></h2>

        <hr />

        <jhi-alert-error></jhi-alert-error>

        <jhi-alert></jhi-alert>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="photoStoreApp.cart.id">Id</span></dt>
          <dd>
            <span>{{ cart()!.id }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.cart.total">Total</span></dt>
          <dd>
            <span>{{ cart()!.total }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.cart.payment">Payment</span></dt>
          <dd>
            @if (cart()!.payment) {
              <div>
                <a [routerLink]="['/payment-my-suffix', cart()!.payment?.id, 'view']">{{ cart()!.payment?.id }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/cart-my-suffix', cart()!.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>

// Project/src/main/webapp/app/entities/cart-my-suffix/cart-my-suffix-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import {} from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './cart-my-suffix.reducer';

export const CartMySuffixDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const cartEntity = useAppSelector(state => state.cart.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="cartDetailsHeading">Cart</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">Id</span>
          </dt>
          <dd>{cartEntity.id}</dd>
          <dt>
            <span id="total">Total</span>
          </dt>
          <dd>{cartEntity.total}</dd>
          <dt>Payment</dt>
          <dd>{cartEntity.payment ? cartEntity.payment.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/cart-my-suffix" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/cart-my-suffix/${cartEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default CartMySuffixDetail;
