// AngularProject/src/main/webapp/app/entities/user-my-suffix/detail/user-my-suffix-detail.component.ts
import { Component, inject, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { DataUtils } from 'app/core/util/data-util.service';
import { IUserMySuffix } from '../user-my-suffix.model';

@Component({
  standalone: true,
  selector: 'jhi-user-my-suffix-detail',
  templateUrl: './user-my-suffix-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class UserMySuffixDetailComponent {
  user = input<IUserMySuffix | null>(null);

  protected dataUtils = inject(DataUtils);

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (user()) {
      <div>
        <h2 data-cy="userDetailsHeading"><span jhiTranslate="photoStoreApp.user.detail.title">User</span></h2>

        <hr />

        <jhi-alert-error></jhi-alert-error>

        <jhi-alert></jhi-alert>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="photoStoreApp.user.id">Id</span></dt>
          <dd>
            <span>{{ user()!.id }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.user.email">Email</span></dt>
          <dd>
            <span>{{ user()!.email }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.user.password">Password</span></dt>
          <dd>
            <span>{{ user()!.password }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.user.address">Address</span></dt>
          <dd>
            <span>{{ user()!.address }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.user.contact">Contact</span></dt>
          <dd>
            <span>{{ user()!.contact }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.user.profilePhoto">Profile Photo</span></dt>
          <dd>
            @if (user()!.profilePhoto) {
              <div>
                <a (click)="openFile(user()!.profilePhoto ?? '', user()!.profilePhotoContentType)">
                  <img
                    [src]="'data:' + user()!.profilePhotoContentType + ';base64,' + user()!.profilePhoto"
                    style="max-width: 100%"
                    alt="user"
                  />
                </a>
                {{ user()!.profilePhotoContentType }}, {{ byteSize(user()!.profilePhoto ?? '') }}
              </div>
            }
          </dd>
          <dt><span jhiTranslate="photoStoreApp.user.portfolio">Portfolio</span></dt>
          <dd>
            @if (user()!.portfolio) {
              <div>
                <a [routerLink]="['/portfolio-my-suffix', user()!.portfolio?.id, 'view']">{{ user()!.portfolio?.id }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/user-my-suffix', user()!.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>

// Project/src/main/webapp/app/entities/user-my-suffix/user-my-suffix-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { openFile, byteSize } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './user-my-suffix.reducer';

export const UserMySuffixDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const userEntity = useAppSelector(state => state.user.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="userDetailsHeading">User</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">Id</span>
          </dt>
          <dd>{userEntity.id}</dd>
          <dt>
            <span id="email">Email</span>
          </dt>
          <dd>{userEntity.email}</dd>
          <dt>
            <span id="password">Password</span>
          </dt>
          <dd>{userEntity.password}</dd>
          <dt>
            <span id="address">Address</span>
          </dt>
          <dd>{userEntity.address}</dd>
          <dt>
            <span id="contact">Contact</span>
          </dt>
          <dd>{userEntity.contact}</dd>
          <dt>
            <span id="profilePhoto">Profile Photo</span>
          </dt>
          <dd>
            {userEntity.profilePhoto ? (
              <div>
                {userEntity.profilePhotoContentType ? (
                  <a onClick={openFile(userEntity.profilePhotoContentType, userEntity.profilePhoto)}>
                    <img
                      src={`data:${userEntity.profilePhotoContentType};base64,${userEntity.profilePhoto}`}
                      style={{ maxHeight: '30px' }}
                    />
                  </a>
                ) : null}
                <span>
                  {userEntity.profilePhotoContentType}, {byteSize(userEntity.profilePhoto)}
                </span>
              </div>
            ) : null}
          </dd>
          <dt>Portfolio</dt>
          <dd>{userEntity.portfolio ? userEntity.portfolio.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/user-my-suffix" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/user-my-suffix/${userEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default UserMySuffixDetail;
