// Project/src/main/webapp/app/entities/receipt-my-suffix/receipt-my-suffix-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import {} from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './receipt-my-suffix.reducer';

export const ReceiptMySuffixDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const receiptEntity = useAppSelector(state => state.receipt.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="receiptDetailsHeading">Receipt</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">Id</span>
          </dt>
          <dd>{receiptEntity.id}</dd>
          <dt>
            <span id="idPayment">Id Payment</span>
          </dt>
          <dd>{receiptEntity.idPayment}</dd>
          <dt>
            <span id="description">Description</span>
          </dt>
          <dd>{receiptEntity.description}</dd>
        </dl>
        <Button tag={Link} to="/receipt-my-suffix" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/receipt-my-suffix/${receiptEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default ReceiptMySuffixDetail;

// AngularProject/src/main/webapp/app/entities/receipt-my-suffix/detail/receipt-my-suffix-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { IReceiptMySuffix } from '../receipt-my-suffix.model';

@Component({
  standalone: true,
  selector: 'jhi-receipt-my-suffix-detail',
  templateUrl: './receipt-my-suffix-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class ReceiptMySuffixDetailComponent {
  receipt = input<IReceiptMySuffix | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (receipt()) {
      <div>
        <h2 data-cy="receiptDetailsHeading"><span jhiTranslate="photoStoreApp.receipt.detail.title">Receipt</span></h2>

        <hr />

        <jhi-alert-error></jhi-alert-error>

        <jhi-alert></jhi-alert>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="photoStoreApp.receipt.id">Id</span></dt>
          <dd>
            <span>{{ receipt()!.id }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.receipt.idPayment">Id Payment</span></dt>
          <dd>
            <span>{{ receipt()!.idPayment }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.receipt.description">Description</span></dt>
          <dd>
            <span>{{ receipt()!.description }}</span>
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/receipt-my-suffix', receipt()!.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>
