// Project/src/main/webapp/app/entities/payment-my-suffix/payment-my-suffix-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './payment-my-suffix.reducer';

export const PaymentMySuffixDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const paymentEntity = useAppSelector(state => state.payment.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="paymentDetailsHeading">Payment</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">Id</span>
          </dt>
          <dd>{paymentEntity.id}</dd>
          <dt>
            <span id="idCart">Id Cart</span>
          </dt>
          <dd>{paymentEntity.idCart}</dd>
          <dt>
            <span id="date">Date</span>
          </dt>
          <dd>{paymentEntity.date ? <TextFormat value={paymentEntity.date} type="date" format={APP_LOCAL_DATE_FORMAT} /> : null}</dd>
          <dt>Receipt</dt>
          <dd>{paymentEntity.receipt ? paymentEntity.receipt.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/payment-my-suffix" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/payment-my-suffix/${paymentEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default PaymentMySuffixDetail;

// AngularProject/src/main/webapp/app/entities/payment-my-suffix/detail/payment-my-suffix-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { IPaymentMySuffix } from '../payment-my-suffix.model';

@Component({
  standalone: true,
  selector: 'jhi-payment-my-suffix-detail',
  templateUrl: './payment-my-suffix-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class PaymentMySuffixDetailComponent {
  payment = input<IPaymentMySuffix | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (payment()) {
      <div>
        <h2 data-cy="paymentDetailsHeading"><span jhiTranslate="photoStoreApp.payment.detail.title">Payment</span></h2>

        <hr />

        <jhi-alert-error></jhi-alert-error>

        <jhi-alert></jhi-alert>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="photoStoreApp.payment.id">Id</span></dt>
          <dd>
            <span>{{ payment()!.id }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.payment.idCart">Id Cart</span></dt>
          <dd>
            <span>{{ payment()!.idCart }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.payment.date">Date</span></dt>
          <dd>
            <span>{{ payment()!.date | formatMediumDate }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.payment.receipt">Receipt</span></dt>
          <dd>
            @if (payment()!.receipt) {
              <div>
                <a [routerLink]="['/receipt-my-suffix', payment()!.receipt?.id, 'view']">{{ payment()!.receipt?.id }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/payment-my-suffix', payment()!.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>
