// AngularProject/src/main/webapp/app/entities/portfolio-my-suffix/detail/portfolio-my-suffix-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { IPortfolioMySuffix } from '../portfolio-my-suffix.model';

@Component({
  standalone: true,
  selector: 'jhi-portfolio-my-suffix-detail',
  templateUrl: './portfolio-my-suffix-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class PortfolioMySuffixDetailComponent {
  portfolio = input<IPortfolioMySuffix | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (portfolio()) {
      <div>
        <h2 data-cy="portfolioDetailsHeading"><span jhiTranslate="photoStoreApp.portfolio.detail.title">Portfolio</span></h2>

        <hr />

        <jhi-alert-error></jhi-alert-error>

        <jhi-alert></jhi-alert>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="photoStoreApp.portfolio.id">Id</span></dt>
          <dd>
            <span>{{ portfolio()!.id }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.portfolio.date">Date</span></dt>
          <dd>
            <span>{{ portfolio()!.date | formatMediumDate }}</span>
          </dd>
          <dt><span jhiTranslate="photoStoreApp.portfolio.name">Name</span></dt>
          <dd>
            <span>{{ portfolio()!.name }}</span>
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/portfolio-my-suffix', portfolio()!.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>

// Project/src/main/webapp/app/entities/portfolio-my-suffix/portfolio-my-suffix-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './portfolio-my-suffix.reducer';

export const PortfolioMySuffixDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const portfolioEntity = useAppSelector(state => state.portfolio.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="portfolioDetailsHeading">Portfolio</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">Id</span>
          </dt>
          <dd>{portfolioEntity.id}</dd>
          <dt>
            <span id="date">Date</span>
          </dt>
          <dd>{portfolioEntity.date ? <TextFormat value={portfolioEntity.date} type="date" format={APP_LOCAL_DATE_FORMAT} /> : null}</dd>
          <dt>
            <span id="name">Name</span>
          </dt>
          <dd>{portfolioEntity.name}</dd>
        </dl>
        <Button tag={Link} to="/portfolio-my-suffix" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/portfolio-my-suffix/${portfolioEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default PortfolioMySuffixDetail;
